server:
  port: 8081

#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        order_inserts: true
  datasource:
    # ImMemory
    #url: jdbc:h2:mem:bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:bootjava
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/db/bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/db/bootjava
    # Relative path form current dir
    #    url: jdbc:h2:./db/bootjava
    # Relative path from home
    #    url: jdbc:h2:~/bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/~/bootjava
    #username: sa
    #password:
    #HSQLDB:
    url: jdbc:hsqldb:mem:restvoting;DB_CLOSE_DELAY=-1
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  transaction:
    management:
      annotation-driven: true

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc: TRACE
    ru.javaops.bootjava: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: TRACE

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

springdoc.swagger-ui.path: /

jwt-secret-key: SECRET